### ISSUE TITLE
Unable to make shsh for apple watch

### ISSUE THREAD

**Issue by amats211** [1Conan/tsschecker#22]
Hi,

I am trying to make shsh for apple watch S3 but tsschecker says Watch3,2 cound nout be found on devicelist.

Anyway to make it work?

TIA

**Comment by DanTheMann15** [comment]
tsschecker grabs the device list from firmwares.json, but because apple doesn't publicly provide ipsw images for the apple watches, firmwares.json doesn't support apple watch.

if you want to save blobs for an apple watch, you will need to get the firmware yourself and extract the buildmanifest from it.
also make sure to get the ECID for your apple watch or you can't re-use the apticket.

even then, you need an iBUS dongle to restore an apple watch ipsw, and there's no jailbreak for them so there isn't much point to saving blobs for an apple watch, you also won't be able to set the nonce generator without a jailbreak or a bootrom exploit (except in the series 3 "checkm8" but again, requires an iBUS dongle).

only in certain limited circumstances is there a point to saving apple watch blobs.

**Comment by amats211** [comment]
Thank you very much for the answer. I do have an adapter for watch, what do i do with buildmanifest extracted from firmware?

Yes i am trying to make one for s3, because i would like to try and patch the boot chain files.

**Comment by DanTheMann15** [comment]
pass `-m` and give it the path to the extracted buildmanifest e.g `-m /path/to/BuildManifest.plist` you don't need to specify a version or build number.

example full use is `tsschecker -d Watch3,2 -B N111bAP -e ECID -m BuildManifest.plist -g GEN -s`

you can also pass -b if you don't use baseband tickets.
